spring:
  application:
    name: ecommerce
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://mongo:OHJIYZLCVFMgomNbSRWWpHnTVOMODnvF@mongodb.railway.internal:27017
      user: mongo
      password: OHJIYZLCVFMgomNbSRWWpHnTVOMODnvF
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dholakiya225@gmail.com
    password: pwsa fabq cdnr uvrt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true      # This is the missing piece
            required: true

cloudinary:
  cloud_name: dnktm0tvo
  api_key : 493347339972695
  api_secret: z3b4g5gECSrcXy9kFjmdhCUA-NE

twilio:
  account_sid: AC55a40e36ecdca877cb42242931bc6a05
  auth_token: 215a724dd3eb729134d65a5d9aefb9f9
  phone_number: +15672922390

jwt:
  secret: 4V8p+7Lz9XmQzR7vTqY2nB5xK8jW3mP1a9sV2dF5gH8=
  expiration: 604800000
